## we use the illustrative networks in our paper (Fig.7 and Fig.8) to show how our method works on simple examples 

In [1]:
import numpy as np

implement equation 26

In [2]:
def DHA(i,k,j):
    M_pm = M_mp.transpose()
    denom1 = M_exp[i,:] + I_mm[j,:]
    V_sub = M_ap[:,k]
    #denom2 = np.multiply(V_sub,(M_exp[:,j]+I_aa[:,i]))
    denom2 = np.multiply(V_sub,M_exp[:,j]) +I_aa[:,i]
    DHA_imj =( M_exp[i,:] + M_pm[k,:])[j]*M_ap[i,k]*M_pm[k,j]/np.sqrt(np.linalg.norm(denom1)*np.linalg.norm(denom2))
    return DHA_imj
    

implement equation 25

In [3]:
def DHA_whole(i):
    (num_m,num_p) = M_mp.shape    
    res = np.zeros(num_m)
    for k in range(0,num_p):
        li_paper = []
        for j in range(0,num_m):
            li_paper.append(DHA(i,k,j))
        res += np.array(li_paper)
    return res

generate the adjacency matrix of the networks

network in Fig.7

In [4]:
M_ap = np.array([[1,0,0,0,0,0],[0,1,1,0,0,0],[0,0,0,1,1,0],[0,0,0,0,0,1]])
M_mp = np.array([[0,1,1,0,0,1],[1,0,0,1,1,0],[1,1,0,1,0,1]])
M_exp = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])

m = 3
a = 4

I_aa = np.eye(a,a)
I_mm = np.eye(m,m)

we run DHA on the first 5 years(note that the networks in the first 5 years are identical)

In [5]:
for y in range(0,5): 
    M_exp = M_exp + np.array([DHA_whole(0),DHA_whole(1),DHA_whole(2),DHA_whole(3)])
    print(M_exp)

[[0. 1. 1.]
 [2. 0. 1.]
 [0. 2. 1.]
 [1. 0. 1.]]
[[0.         1.94574161 1.94574161]
 [3.94800749 0.         1.84089642]
 [0.         3.94800749 1.84089642]
 [1.94574161 0.         1.94574161]]
[[0.         2.85920054 2.85920054]
 [5.88422611 0.         2.60514684]
 [0.         5.88422611 2.60514684]
 [2.85920054 0.         2.85920054]]
[[0.         3.75558442 3.75558442]
 [7.81841593 0.         3.32793561]
 [0.         7.81841593 3.32793561]
 [3.75558442 0.         3.75558442]]
[[0.         4.64146726 4.64146726]
 [9.75293768 0.         4.02385654]
 [0.         9.75293768 4.02385654]
 [4.64146726 0.         4.64146726]]


generate the adjacency matrix of the networks in Fig.8 

In [6]:
m = 3
a = 4

I_aa = np.eye(a,a)
I_mm = np.eye(m,m)

# note that we can consider p2,p4,p6 as duplications of p1,p3,p5 rescpective, here we use only 3 papers 
# and each link between authors and papers will be counted twice
M_ap = np.array([[2,0,0],[2,2,0],[0,2,2],[0,0,2]])
M_mp = np.array([[0,1,1],[1,1,0],[1,0,1]])

In [7]:
for y in range(5,10): 
    M_exp = M_exp + np.array([DHA_whole(0),DHA_whole(1),DHA_whole(2),DHA_whole(3)])
    print(M_exp)

[[ 0.          5.943256    5.79668841]
 [11.15454075  0.34007483  4.86641174]
 [ 0.34007483 11.15454075  4.86641174]
 [ 5.943256    0.          5.79668841]]
[[ 0.          7.22860575  6.93064691]
 [12.54554431  0.72308559  5.6977417 ]
 [ 0.72308559 12.54554431  5.6977417 ]
 [ 7.22860575  0.          6.93064691]]
[[ 0.          8.50202078  8.04953329]
 [13.92719556  1.14878544  6.52094035]
 [ 1.14878544 13.92719556  6.52094035]
 [ 8.50202078  0.          8.04953329]]
[[ 0.          9.76607508  9.15712499]
 [15.30036816  1.61676346  7.33788128]
 [ 1.61676346 15.30036816  7.33788128]
 [ 9.76607508  0.          9.15712499]]
[[ 0.         11.02234327 10.25591674]
 [16.66567376  2.1265307   8.14977916]
 [ 2.1265307  16.66567376  8.14977916]
 [11.02234327  0.         10.25591674]]
